server:
  port: 8089
  
spring:
  r2dbc:
    url: r2dbc:postgresql://db.${SUPABASE_PROJECT_REF_IMPORTED}.supabase.co:5432/postgres
    username: postgres
    password: ${SUPABASE_DB_PASSWORD}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org.springframework.web.reactive: DEBUG
    org.springframework.data.r2dbc: DEBUG
    io.github.resilience4j: INFO

resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
    instances:
      planPrecioServiceCB:
        base-config: default
      transaccionPagoServiceCB:
        base-config: default

---

SUPABASE_PROJECT_REF_IMPORTED: jtnsigjcpxhkxhpbotkv
SUPABASE_DB_PASSWORD: alternatica-skilling
